engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
ratings:
  paths:
  - packages/ability/src/**
  - packages/mongoose/src/**
exclude_paths:
- packages/ability/spec/**/*
- packages/mongoose/spec/**/*
- docs/**/*
