packages:
  - packages/*

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  # Renovate security update: @casl/ability@6.7.5
  - "@casl/ability@6.7.5"
  # Renovate security update: rollup@4.59.0
  - rollup@4.59.0
