packages:
  - packages/*

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  # Renovate security update: @casl/ability@6.7.5
  - "@casl/ability@6.7.5"
  # Renovate security update: @angular/core@21.1.6 || 21.2.4
  - "@angular/core@21.1.6 || 21.2.4"
  # Renovate security update: rollup@4.59.0
  - rollup@4.59.0
  # Renovate security update: @angular/compiler@21.2.4
  - "@angular/compiler@21.2.4"
  - "@ucast/mongo2js@2.0.0"
  - "@ucast/js@4.0.1"
  - "@ucast/mongo@3.0.0"
  - "@ucast/core@2.0.0"
